import type { Metadata } from "next";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Navbar from "@/app/components/Navbar";

export const metadata: Metadata = {
  title: "Unicareer",
  description: "Generated by team C",
  icons:{
    icon:'/img/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
          <Navbar />
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
